version: '3.9'

services:
  client:
    build: ./client
    working_dir: /client
    ports:
      - 4000:4000
    container_name: client
    volumes:
      - ./client:/client
    networks:
      - client_server
    depends_on:
      - server

  server:
    build: ./server
    working_dir: /server
    ports:
      - 3000:3000
    volumes:
      - ./server:/server
    networks:
      - client_server
      - db_server
    depends_on:
      - db
    
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
    volumes:
      - db:/var/lib/mysql
    networks:
      - db_server
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - db_server


volumes:
  db:

networks:
  client_server:
  db_server:
