version: '3.9'

services:
  client:
    build: ./client
    working_dir: /client
    ports:
      - 4000:4000
    container_name: client
    networks:
      - client_server
    depends_on:
      - server

  server:
    build: ./server
    working_dir: /server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/server
      - server_nodemodules:/server/node_modules/
    networks:
      - client_server
      - db_server
    depends_on:
      - db
    
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - db_server
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - db_server


volumes:
  server_nodemodules:
  client_nodemodules:
  db:

networks:
  client_server:
  db_server:
